[tools]
act = "latest"
actionlint = "latest"
"aqua:vercel-labs/agent-browser" = "latest"
bun = "latest"
"github:codecoradev/cora-code" = "latest"
"github:fatedier/frp" = "latest"
"github:universal-ctags/ctags-nightly-build" = "latest"
lefthook = "latest"
node = "24"
"npm:greptile" = "latest"

[env]
_.path = ["./node_modules/.bin"]
